services:
  mongodb:
    image: mongo
    ports: ["27017:27017"]

  redis:
    image: redis
    ports: ["6379:6379"]

  kafka:
    image: bitnami/kafka:latest
    ports: ["9092:9092"]
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    image: bitnami/zookeeper:latest
    ports: ["2181:2181"]
    
  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on: [auth, event, redis]

  auth:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on: [mongodb, redis]

  event:
    build:
      context: ./apps/event
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    depends_on: [kafka, redis, mongodb]