services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    
  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/gateway:/app
      - /app/node_modules
    depends_on:
      - auth
      - event
      - redis

  auth:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./apps/auth:/app
      - /app/node_modules
    depends_on:
      - mongodb

  event:
    build:
      context: ./apps/event
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ./apps/event:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - kafka

volumes:
  mongo_data: {}