# Node 18 
FROM node:18

# 작업 디렉토리 
WORKDIR /app

# package.json과 lock 파일 복사
COPY package*.json ./

# 의존성 설치
RUN npm install -g @nestjs/cli && npm install

# 소스 코드 복사
COPY . .

# NestJS 개발 서버 실행
CMD ["npm", "run", "start:dev"]